[images]
remote_images = []

[[headers]]
for = "/_astro/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[context]

  [context.production]

    [context.production.images]
    remote_images = []

    [[context.production.headers]]
    for = "/_astro/*"

      [context.production.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context."deploy/masonry-from-tag"]

    [context."deploy/masonry-from-tag".images]
    remote_images = []

    [[context."deploy/masonry-from-tag".headers]]
    for = "/_astro/*"

      [context."deploy/masonry-from-tag".headers.values]
      Cache-Control = "public, max-age=31536000, immutable"